INSERT ALL
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1001','Spaghetti Bolognese','Classic Italian dish consisting of spaghetti pasta topped with a rich tomato-based meat sauce.','Mama Mia Italian Kitchen')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1002','Grilled Salmon','Fresh fillet of salmon seasoned and grilled to perfection, served with steamed vegetables and lemon butter sauce.','Ocean Bounty Seafood Market')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1003','Chicken Caesar Salad','Crisp romaine lettuce tossed with grilled chicken breast, Caesar dressing, Parmesan cheese, and croutons.','Fresh Greens Farm')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1004','Beef Tacos','Soft corn tortillas filled with seasoned ground beef, shredded lettuce, diced tomatoes, cheese, and salsa.','Fiesta Fresh Mexican Grill')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1005','Vegetable Stir-Fry','Assorted vegetables stir-fried in a savory sauce, served over steamed rice.','Green Valley Produce Market')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1006','Margherita Pizza','Traditional Italian pizza topped with fresh tomatoes, mozzarella cheese, basil leaves, and olive oil.','Tony Pizzeria')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1007','Beef Stroganoff','Tender strips of beef cooked in a creamy mushroom sauce, served over egg noodles.','Grandma Kitchen Deli')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1008','Sushi Platter','Assortment of fresh sushi rolls and sashimi pieces, accompanied by soy sauce, wasabi, and pickled ginger.','Tokyo Sushi Bar')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1009','Veggie Burger','Plant-based burger patty served on a toasted bun with lettuce, tomato, onion, and special sauce.','Green Eats Vegan Cafe')
    INTO MEAL (meal_id, meal_name, meal_description, supplier) VALUES ('1010','Chicken Alfredo Pasta','Fettuccine pasta tossed in a creamy Alfredo sauce with grilled chicken, garlic, and Parmesan cheese.','Bella Italia Trattoria')
SELECT 1 FROM DUAL;