-- INSERT ALL
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP001','1')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP002','2')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP003','3')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP004','4')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP005','5')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP006','6')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP007','7')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP008','8')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP009','9')
--     INTO PAYMENT (transaction_id, account_id) VALUES ('BP010','10')
-- SELECT 1 FROM DUAL;
