INSERT ALL
    INTO (transaction_id, employee_id) VALUES ('BP001','1')
    INTO (transaction_id, employee_id) VALUES ('BP002','2')
    INTO (transaction_id, employee_id) VALUES ('BP003','3')
    INTO (transaction_id, employee_id) VALUES ('BP004','4')
    INTO (transaction_id, employee_id) VALUES ('BP005','5')
    INTO (transaction_id, employee_id) VALUES ('BP006','6')
    INTO (transaction_id, employee_id) VALUES ('BP007','7')
    INTO (transaction_id, employee_id) VALUES ('BP008','8')
    INTO (transaction_id, employee_id) VALUES ('BP009','9')
    INTO (transaction_id, employee_id) VALUES ('BP010','10')