CREATE SEQUENCE ML_ID_SEQUENCE
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0;

CREATE OR REPLACE TRIGGER ML_ID_AUTO_INCREMENT
    BEFORE INSERT ON MAINTENANCE_LOG
    FOR EACH ROW
BEGIN
    :NEW.MAINTENANCE_LOG_ID := ML_ID_SEQUENCE.NEXTVAL;
END;
/