CREATE SEQUENCE ACCOUNT_ID_SEQUENCE
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    CACHE 100;

CREATE OR REPLACE TRIGGER ACCOUNT_ID_AUTO_INCREMENT
    BEFORE INSERT ON ACCOUNT
    FOR EACH ROW
BEGIN
    :NEW.ACCOUNT_ID := ACCOUNT_ID_SEQUENCE.NEXTVAL;
END;
/