CREATE SEQUENCE MEAL_ID_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE OR REPLACE TRIGGER MEAL_ID_AUTO_INCREMENT
    BEFORE INSERT ON MEAL
    FOR EACH ROW
BEGIN
    :NEW.MEAL_ID := ACCOUNT_ID_SEQUENCE.NEXTVAL;
END;
/