CREATE SEQUENCE OFFER_ID_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE OR REPLACE TRIGGER OFFER_ID_AUTO_INCREMENT
    BEFORE INSERT ON OFFER
    FOR EACH ROW
BEGIN
    :NEW.OFFER_ID := OFFER_ID_SEQUENCE.NEXTVAL;
END;