CREATE SEQUENCE BAGGAGE_ID_SEQUENCE
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    CACHE 100;

CREATE OR REPLACE TRIGGER BAGGAGE_ID_AUTO_INCREMENT
    BEFORE INSERT ON BAGGAGE
    FOR EACH ROW
BEGIN
    :NEW.BAGGAGE_ID := BAGGAGE_ID_SEQUENCE.NEXTVAL;
END;
/