CREATE OR REPLACE TRIGGER FT_ID_AUTO_INCREMENT
    BEFORE INSERT ON FLIGHT_TICKET
    FOR EACH ROW
DECLARE
    last_ticket_id NUMBER;
BEGIN
    SELECT NVL(COUNT(*), 1) INTO last_ticket_id FROM FLIGHT_TICKET WHERE FLIGHT_TICKET_ID LIKE ('SFS' || TO_CHAR(:NEW.DATETIME_PLACED, 'IYMM') || '%');
    :NEW.FLIGHT_TICKET_ID := ('SFS' || TO_CHAR(:NEW.DATETIME_PLACED, 'IYMM') || LPAD(last_ticket_id + 1, 6, '0'));
END;
/