CREATE SEQUENCE EMPLOYEE_ID_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    CACHE 100;

CREATE OR REPLACE TRIGGER EMPLOYEE_ID_AUTO_INCREMENT
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
BEGIN
    :NEW.EMPLOYEE_ID := EMPLOYEE_ID_SEQUENCE.NEXTVAL;
END;