CREATE OR REPLACE TRIGGER SEAT_ID_AUTO_INCREMENT
    BEFORE INSERT ON SEAT
    FOR EACH ROW
DECLARE
    last_seat_id NUMBER;
BEGIN
    SELECT NVL(COUNT(*), 1) INTO last_seat_id FROM SEAT WHERE AIRCRAFT_ID = :NEW.AIRCRAFT_ID;
    :NEW.SEAT_ID := (:NEW.AIRCRAFT_ID || LPAD(last_seat_id + 1, 4, '0'));
END;