CREATE SEQUENCE TRANSACTION_ID_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    CACHE 100

CREATE OR REPLACE TRIGGER TRANSACTION_ID_AUTO_INCREMENT
    BEFORE INSERT ON TRANSACTION
    FOR EACH ROW
BEGIN
    :NEW.TRANSACTION_ID := ('T' || LPAD(TRANSACTION_ID_SEQUENCE.NEXTVAL, 9, '0'));
END;
/