CREATE SEQUENCE PAYCHECK_ID_SEQUENCE
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    CACHE 50;

CREATE OR REPLACE TRIGGER PAYCHECK_ID_AUTO_INCREMENT
    BEFORE INSERT ON PAYCHECK
    FOR EACH ROW
BEGIN
    :NEW.PAYCHECK_ID := ('EP' || LPAD(PAYCHECK_ID_SEQUENCE.NEXTVAL, 8, '0'));
END;
/