CREATE SEQUENCE PILOT_ID_SEQUENCE
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    CACHE 10;

CREATE OR REPLACE TRIGGER PILOT_ID_AUTO_INCREMENT
    BEFORE INSERT ON PILOT
    FOR EACH ROW
BEGIN
    :NEW.PILOT_ID := ('PL' || LPAD(PILOT_ID_SEQUENCE.NEXTVAL, 4, '0'));
END;
/