CREATE SEQUENCE MEMBERSHIP_ID_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE OR REPLACE TRIGGER MEMBERSHIP_ID_AUTO_INCREMENT
    BEFORE INSERT ON MEMBERSHIP
    FOR EACH ROW
BEGIN
    :NEW.MEMBERSHIP_ID := MEMBERSHIP_ID_SEQUENCE.NEXTVAL;
END;
/