SET LINESIZE 140;
SET PAGESIZE 50;
SET VERIFY OFF;
SET FEEDBACK OFF;
SET SERVEROUT ON;

COLUMN "Route ID" FORMAT A10
COLUMN "Depart Country" FORMAT A40 TRUNCATED
COLUMN "Arrive Country" FORMAT A40 TRUNCATED
COLUMN "Total Flights" FORMAT 99999999999
COLUMN "Booked Count" FORMAT 99999999999
COLUMN "Cancelled Count" FORMAT 99999999999

BREAK ON "Depart Country" SKIP PAGE ON "Arrive Country" SKIP 1;

COMPUTE SUM LABEL 'Total' OF "Cancelled Count" ON "Arrive Country" "Depart Country";
COMPUTE SUM LABEL 'Total of Country' OF "Booked Count" ON "Arrive Country" "Depart Country";

ACCEPT v_month   DATE FORMAT 'MM/YYYY'  PROMPT "Enter the Month you like to view. (MM/YYYY)         : ";
ACCEPT v_country CHAR DEFAULT NULL      PROMPT "Enter the Country to filter (Leave Empty for All)   : ";
ACCEPT v_sort CHAR DEFAULT DESC         PROMPT "Sort sales by ASCENDING or DESCENDING? (ASC | DESC) : ";

TTITLE -
    CENTER 'Ticket Sales Overview on Countries' SKIP 1 -
    CENTER '----------------------------------' SKIP 2 -
    RIGHT 'Page No: ' FORMAT 99 SQL.PNO SKIP 2;

SELECT
    R.ROUTE_ID AS "Route ID",
    C1.COUNTRY_NAME AS "Depart Country",
    C2.COUNTRY_NAME AS "Arrive Country",
    COUNT(F.FLIGHT_ID) AS "Total Flights",
    (
    SELECT COUNT(*)
    FROM ROUTE
        JOIN FLIGHT ON ROUTE.ROUTE_ID = FLIGHT.ROUTE_ID
        JOIN FLIGHT_SEQUENCE ON FLIGHT.FLIGHT_ID = FLIGHT_SEQUENCE.FLIGHT_ID
        JOIN FLIGHT_TICKET ON FLIGHT_SEQUENCE.FLIGHT_TICKET_ID = FLIGHT_TICKET.FLIGHT_TICKET_ID
    WHERE ROUTE.ROUTE_ID = R.ROUTE_ID AND TICKET_STATUS = 'Completed'
    ) AS "Booked Count",
    (
    SELECT COUNT(*)
    FROM ROUTE
        JOIN FLIGHT ON ROUTE.ROUTE_ID = FLIGHT.ROUTE_ID
        JOIN FLIGHT_SEQUENCE ON FLIGHT.FLIGHT_ID = FLIGHT_SEQUENCE.FLIGHT_ID
        JOIN FLIGHT_TICKET ON FLIGHT_SEQUENCE.FLIGHT_TICKET_ID = FLIGHT_TICKET.FLIGHT_TICKET_ID
    WHERE ROUTE.ROUTE_ID = R.ROUTE_ID AND TICKET_STATUS = 'Cancelled'
    ) AS "Cancelled Count"
FROM ROUTE R
    JOIN AIRPORT A1 ON R.FROM_AIRPORT_ID = A1.AIRPORT_ID
    JOIN AIRPORT A2 ON R.TO_AIRPORT_ID = A2.AIRPORT_ID
    JOIN COUNTRY C1 ON A1.COUNTRY_ID = C1.COUNTRY_ID
    JOIN COUNTRY C2 ON A2.COUNTRY_ID = C2.COUNTRY_ID
    LEFT JOIN FLIGHT F ON R.ROUTE_ID = F.ROUTE_ID
WHERE MONTHS_BETWEEN(F.DEPARTURE_DATETIME, TO_DATE('01/&v_month', 'DD/MM/YYYY')) BETWEEN 0 AND 1
    AND C1.COUNTRY_NAME = CASE '&v_country'
    WHEN 'NULL' THEN C1.COUNTRY_NAME
    ELSE '&v_country'
    END
GROUP BY R.ROUTE_ID, C1.COUNTRY_NAME, C2.COUNTRY_NAME
ORDER BY SUM("Booked Count") OVER ( PARTITION BY C1.COUNTRY_NAME ) &v_sort, SUM("Booked Count") OVER ( PARTITION BY C2.COUNTRY_NAME ) &v_sort, C1.COUNTRY_NAME, C2.COUNTRY_NAME;

TTITLE OFF;
CLEAR COLUMNS;
CLEAR BREAKS;
CLEAR COMPUTES;