SET LINESIZE 104;
SET PAGESIZE 100;

TTITLE CENTER  'Customer Analysis for' FORMAT DATE _DATE RIGHT 'Page No: ' FORMAT 99 SQL.PNO SKIP 2;

COLUMN CUST_NAME FORMAT A15;
COLUMN ORDER_DATE FORMAT A10;
COLUMN DESCRIPTION FORMAT A25 TRUNCATED;
COLUMN PRICE FORMAT $999.99;
COLUMN SUB_TOTAL FORMAT &9999.99;

BREAK ON CUST_NO SKIP PAGE ON CUST_NAME ON ORDER_NO SKIP 1 ON ORDER_DATE;

COMPUTE SEM LABEL 'Total' OF SUB_TOTAL QUANTITY PRICE ON ORDER_NO;
COMPUTE SEM LABEL 'Speding' OF SUB_TOTAL ON CUST_NO;

SELECT 
FROM
WHERE

TTITLE OFF;
CLEAR COLUMNS;
CLEAR BREAKS;
CLEAR COMPUTES;