-- Query Plane Idle Time
SELECT
    AIRCRAFT_ID,
    LAG(DEPARTURE_DATETIME) OVER (ORDER BY AIRCRAFT_ID, DEPARTURE_DATETIME) AS "Last Departure",
    LAG(DEPARTURE_DATETIME + EST_DURATION_IN_HOUR / 24) OVER (ORDER BY AIRCRAFT_ID, DEPARTURE_DATETIME) AS "Expected Arrival / Idle Start",
    DEPARTURE_DATETIME AS "Next Departure Time",
    DEPARTURE_DATETIME - LAG(DEPARTURE_DATETIME + EST_DURATION_IN_HOUR / 24) OVER (ORDER BY AIRCRAFT_ID, DEPARTURE_DATETIME) AS "Idle Duration"
FROM FLIGHT
ORDER BY AIRCRAFT_ID, DEPARTURE_DATETIME;

-- Seat Book Rate
SELECT
    FLIGHT.FLIGHT_ID AS "Flight ID",
    AIRCRAFT_MODEL.MODEL_NAME,
    DEPARTURE_DATETIME AS "Departure Time",
    COUNT(FLIGHT_SEQUENCE.SEAT_ID) AS "Number of Seats Booked",
    NUMBER_OF_SEAT AS "Aircraft Seats",
    TO_CHAR(COUNT(FLIGHT_SEQUENCE.SEAT_ID) / NUMBER_OF_SEAT * 100, '990.99') || '%' AS "Percentage Booked"
FROM FLIGHT
    JOIN FLIGHT_SEQUENCE ON FLIGHT.FLIGHT_ID = FLIGHT_SEQUENCE.FLIGHT_ID
    JOIN SEAT ON FLIGHT_SEQUENCE.SEAT_ID = SEAT.SEAT_ID
    JOIN AIRCRAFT ON FLIGHT.AIRCRAFT_ID = AIRCRAFT.AIRCRAFT_ID
    JOIN AIRCRAFT_MODEL ON AIRCRAFT.AIRCRAFT_MODEL_ID = AIRCRAFT_MODEL.AIRCRAFT_MODEL_ID
GROUP BY FLIGHT.FLIGHT_ID, DEPARTURE_DATETIME, AIRCRAFT.AIRCRAFT_MODEL_ID, NUMBER_OF_SEAT, MODEL_NAME
ORDER BY DEPARTURE_DATETIME;

-- Find Overbooked Seats
SELECT
    FLIGHT.FLIGHT_ID,
    DEPARTURE_DATETIME,
    SEAT.SEAT_ID,
    COUNT(*)
FROM FLIGHT_SEQUENCE
    JOIN FLIGHT ON FLIGHT_SEQUENCE.FLIGHT_ID = FLIGHT.FLIGHT_ID
    JOIN SEAT ON FLIGHT_SEQUENCE.SEAT_ID = SEAT.SEAT_ID
HAVING COUNT(*) > 1
GROUP BY FLIGHT.FLIGHT_ID, DEPARTURE_DATETIME, SEAT.SEAT_ID
ORDER BY FLIGHT.FLIGHT_ID;

